version: 0.0
os: linux 
files:
  - source: /app/
    destination: /home/ubuntu/app/
hooks:
  AfterInstall:
    - location: pipeline-scripts/set-envfile.sh
      timeout: 60
    - location: pipeline-scripts/run-app.sh
      timeout: 60
